name: Build executables

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 6 1 * *' # Run 1st of every month at 06:00 UTC

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y automake autoconf libtool
      - run: aclocal
      - run: libtoolize
      - run: automake --add-missing
      - run: autoconf

      - run: ./configure
      - run: make
      - run: sudo make install

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install automake autoconf libtool wxwidgets
      - run: aclocal
      - run: glibtoolize
      - run: automake --add-missing
      - run: autoconf

      - run: ./configure
      - run: make
      - run: sudo make install
      - run: make osx-bundle

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          install: mingw-w64-x86_64-toolchain make automake autoconf libtool
      - run: pacman -S --noconfirm mingw-w64-x86_64-wxmsw3.1
      - run: aclocal
      - run: libtoolize
      - run: automake --add-missing
      - run: autoconf

      - run: ./configure --disable-enumpoly --with-wx-config=wx-config-3.1
      - run: make

      - uses: actions/upload-artifact@v2
        with:
          path: |
            libs/**/*gambit*.exe
            contrib/**/*gambit*.exe
            contrib/**/gambit.exe
          retention-days: 32

