name: pygambit Python extension

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython nose2 wheel
          sudo apt-get install libxml2-dev libxslt-dev
      - name: Build extension
        run: |
          cd src
          python setup.py build
          python setup.py install
      - name: Run nosetests
        run: |
          cd src/pygambit/tests
          nose2

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython nose2 wheel lxml
      - name: Build extension
        run: |
          cd src
          python setup.py build
          python setup.py install
      - name: Run nosetests
        run: |
          cd src/pygambit/tests
          nose2
